---
name: 'Lint'
on:
  pull_request: {}
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 * * *'
jobs:
  hacs:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'hacs/action@main'
        with:
          category: 'integration'
          ignore: 'brands'

  hassfest:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'home-assistant/actions/hassfest@master'
  
  python-lint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'ricardochaves/python-lint@v1.4.0'
        with:
          python-root-list: >-
            custom_components/unavailable_entities
            tests

          # TODO: Enable these linters.
          use-pycodestyle: false
          use-mypy: false
  
  yamllint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'ibiqlik/action-yamllint@v3'
