---
name: 'Lint'
on:
  pull_request: {}
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 * * *'
jobs:
  hacs:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'hacs/action@main'
        with:
          category: 'integration'
          ignore: 'brands'

  hassfest:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'home-assistant/actions/hassfest@master'

  pre-commit:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/setup-python@v2'
      - uses: 'pre-commit/action@v2.0.3'
